# Generated by Django 4.2.3 on 2023-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrop',
            name='delivery_status',
            field=models.CharField(choices=[('Active', 'Active'), ('In active', 'In active'), ('Disconnect', 'Disconnect')], default='In active', max_length=50),
        ),
    ]
